### ISSUE TITLE
Add "Under Maintenance" status to component status types

### ISSUE THREAD

**Issue by sde1aney** [CachetHQ/Cachet#2782] opened 2017-10-26 10:01 UTC
The ability to mark components as being in a maintenance state, both automatically for published maintenance items, and manually for urgent unpublished maintenance.

I _think_ I've got the change for the manual selection sorted in my fork. As yet untested.

**Comment by uxen-ab** [comment] 2018-01-15 09:50
I think the maintenance has some issues:

- Once the scheduled time for the maintenance is reached, even if the status is 'upcoming' the maintenance is no longer displayed on the status page.
- After creating a maintenance, the first time we go on the edit page the scheduled time has one hour more (at least in France), perhaps the timezone isn't correct when creating, I don't know.
- The maintenance is no longer in the timeline after it's finished, it could be useful to see or communicate to the customers when there was a maintenance.

Will these points be in your commits? If not, I'll contribute.

**Comment by Wouter0100** [comment] 2018-03-19 21:58
Possible duplicate of #2051?

**Comment by uxen-ab** [comment] 2018-03-20 08:59
@Wouter0100 Indeed it seems to be duplicate. Thanks for pointing this out.
But I have an up to date install of Cachet and I'm unable to set a status "Under maintenance" nor to configure a custom status.
Is it working?

**Comment by Wouter0100** [comment] 2018-03-20 09:00
See the issue. It's not implemented yet, although they're starting to work on it.

**Comment by uxen-ab** [comment] 2018-03-20 09:04
Indeed you're right, I'd misunderstood the end. So this issue should be closed as duplicate I guess.

**Comment by jbrooksuk** [comment] 2018-04-02 16:19
Duplicate of https://github.com/CachetHQ/Cachet/issues/2051

**Closed by jbrooksuk** 2018-04-02 16:19 UTC
