### ISSUE TITLE
Incident template creation not working

### ISSUE THREAD

**Issue by labolanimichele** [CachetHQ/Cachet#2749] opened 2017-10-09 15:36 UTC
Just pulled the latest 2.4

I am now unable to create an incident template: when trying to create one, I can enter text for the "Name" section, but the "Template" section is a non-editable field (the Twig pre-viewer).
Happens also when trying to edit an existing template.

![capture](https://user-images.githubusercontent.com/22618797/31346108-51d2e8bc-ad18-11e7-8d4a-4da857a5e1ae.PNG)

**Comment by jbrooksuk** [comment] 2017-10-11 07:21
Noted. I'll get a fix for this shortly.

**Comment by cringer** [comment] 2017-10-15 07:16
:+1:

**Comment by chesterduane** [comment] 2018-01-04 16:15
Is this already fixed? I am also having same issue. 

![image](https://user-images.githubusercontent.com/20613780/34572832-5ac1b1ae-f1ad-11e7-82c2-1ea3bd737698.png)

**Comment by uxen-ab** [comment] 2018-01-12 14:40
@chesterduane, @labolanimichele The problem is because the text editor (CodeMirror) is initialized before the DOM is fully loaded. I've just submitted a pull request #2866 that fixed this problem.

**Comment by labolanimichele** [comment] 2018-02-23 09:22
Hello - this specific issue is now fixed upon template creation.
However, the editing of existing templates is still showing the same problem.

Thanks,
Michele

**Closed** 2018-03-31 10:54 UTC
Labels: bug :space_invader:, good first issue :rocket:
