### ISSUE TITLE
v2.3.14 (500 Error) Unable to subscribe 

### ISSUE THREAD

**Issue by 3weakley** [CachetHQ/Cachet#2987] opened 2018-04-01 09:08 UTC
Scratching my head on this one, any idea?

I updated from 2.3.13, however I was having this issue before hand. 

[2018-04-01 09:01:35] production.CRITICAL: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function CachetHQ\Cachet\Bus\Handlers\Events\Subscriber\cachet_route()' in /home/cachet/www/app/Bus/Handlers/Events/Subscriber/SendSubscriberVerificationEmailHandler.php:51
Stack trace:
#0 {main} {"identification":{"id":"1e2d3a82-1053-4fb0-8634-e0093a3f451d"}}

----

**.env file**

PP_ENV=production
APP_DEBUG=true
APP_URL=http://localhost
APP_KEY=base64:qDTLp/S2WWGz3MMQi0Z7/L+7doYrptMeXIbd3fFzDWY=

DB_DRIVER=sqlite
DB_DATABASE=/home/cachet/www/database/database.sqlite

CACHE_DRIVER=apc
SESSION_DRIVER=apc
QUEUE_DRIVER=sync
CACHET_EMOJI=false

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_USERNAME=eweakley@esi-esi-estech.com
MAIL_PASSWORD=mypassword
MAIL_ADDRESS=eweakley@esi-estech.com
MAIL_NAME="ESI eService Status Dashboard"
MAIL_ENCRYPTION=ssl

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null

GITHUB_TOKEN=null

**Comment by anthonybocci** [comment] 2018-04-01 20:57
I'm not sure to understand. You have this problem in 2.3.13 and you have it too in 2.3.14?
Are you sure about this error log?
`Call to undefined function CachetHQ\Cachet\Bus\Handlers\Events\Subscriber\cachet_route()`
I've checked in 2.3.13 and 2.3.14, and I've seen no `cachet_route` usage at line 51. Only a `route` usage.

Please give precision, and I'll try to install a 2.3.14 on my machine to reproduce the bug.

**Comment by jbrooksuk** [comment] 2018-04-02 16:16
I can confirm what @anthonybocci is saying, there is no usage of `cachet_route` through the 2.3 codebase.

**Comment by 3weakley** [comment] 2018-04-04 14:55
Hmm, well that's odd @jbrooksuk / @anthonybocci 

I started my installation follows the steps provided by [Digital Ocean](https://www.digitalocean.com/community/tutorials/how-to-create-a-status-page-with-cachet-on-debian-8). on version 2.3.13.

Here is our website
https://cachet.esi-estech.com/

- Do you see anything wrong with my .env file?
- What other logs would be helpful?

Thanks

**Comment by anthonybocci** [comment] 2018-04-04 18:06
@3weakley The thing is your log is _not possible_ in 2.3. Do you have many Cachet instances?

I can confirm I can't subscribe, I got a 500. I think this problem is not a bug and should be managed on Slack, please the next time ask on Slack before creating an issue.

I've got the error log `ca9eb1c9-60d4-4e77-a4bd-0d1bc2aee7d9`, can you post this log?

**Comment by 3weakley** [comment] 2018-04-04 23:42
Hey @anthonybocci , yes I can do that. Thank you

I did create a second directory at one time for the 2.4 release to test if email subscribing would work. That may be what you are thinking about. 

/home/cachet/www - current instance

/home/cachet/esi - old instance that I have since deleted and cleared cache and reset files.

**Comment by anthonybocci** [comment] 2018-04-07 16:26
@jbrooksuk You can close this issue, it's not a bug. It's about a wrong SMTP configuration or something like that, we're speaking about it on Slack.

**Comment by jbrooksuk** [comment] 2018-05-14 07:49
Thanks @anthonybocci

**Closed by jbrooksuk** 2018-05-14 07:49 UTC
