### ISSUE TITLE
Re-arranging components in list triggers email flood

### ISSUE THREAD

**Issue by c0ri** [CachetHQ/Cachet#3518] opened 2019-03-13 10:41 UTC
I have(had) around 75 components. The other day I added a few more and re-arranged the list by dragging/dropping them into new positions.  After that I started getting tons of emails stating 'Component X has been updated'. I'm cleared cache and installed the latest version, and nothing seems to stop it. Today I even deleted all components and started over but still the emails come. I made maintenance events several days ago and still haven't gotten any of those emails. Very strange. Can someone tell me how to clear this mess up?
Thanks!

**Comment by c0ri** [comment] 2019-03-13 11:54
I think I figured it out.
cd /var/www/cachet
php artisan down

mysql -u cachet -p
use cachet;
truncate table jobs;
/q

I had over 5500 jobs still pending emails :( This def needs a fix. Users don't need to be notified when a component is moved around in the list.

Hope this helps someone else.

**Comment by demarant** [comment] 2019-03-18 10:18
confirmed. we can replicate the same issue on cachethq/docker:2.3.15

**Comment by demarant** [comment] 2019-03-18 10:20
seems to be fixed in https://github.com/CachetHQ/Cachet/issues/3228

**Comment by c0ri** [comment] 2019-03-21 02:41
Hi @demarant  Thanks!

$ git tag -l
v0.1.0-alpha
v1.0.0
[...]
v2.3.9

Can someone please tag 2.4? Has it been publicly released?

**Comment by jbrooksuk** [comment] 2019-03-21 08:21
Yeah, this is fixed in 2.4.

> Can someone please tag 2.4? Has it been publicly released?

We're still working on it :)

**Closed by jbrooksuk** 2019-03-21 08:21 UTC
Labels: triage

**Comment by labolanimichele** [comment] 2019-03-21 09:27
Any approximate timeline you‘re looking at?
Most fixes in the latest year got in there

**Comment by labolanimichele** [comment] 2019-03-21 09:27
Any timeline you guys are looking at btw just as an info?

**Comment by jbrooksuk** [comment] 2019-04-12 20:33
Nope, but the 2.4 branch should be mostly stable.

**Comment by c0ri** [comment] 2019-04-14 06:54
Again, can someone please tag this branch or let me know how to grab it?
