### ISSUE TITLE
LDAP Support

### ISSUE THREAD

**Issue by asham0** [CachetHQ/Cachet#3261] opened 2018-09-26 13:53 UTC
Hi,
 I have installed CachetHQ version 2.4.0-dev, I just want to know does it support integration with LDAP.

Please let me know ASAP

Thank You!

**Comment by asham0** [comment] 2018-09-27 05:59
Hello Team,

Please let us know ASAP

Thank you!

**Comment by GrahamCampbell** [comment] 2018-10-31 17:00
LDAP is not currently supported, but if you'd like to implemented, we'll happily review the PR.

**Comment by jbrooksuk** [comment] 2018-12-28 08:07
Duplicate of https://github.com/CachetHQ/Cachet/issues/2108

**Closed by jbrooksuk** 2018-12-28 08:07 UTC
Labels: triage
