### ISSUE TITLE
Be able to set a component on a maintenance task

### ISSUE THREAD

**Issue by stipx** [CachetHQ/Cachet#2044] opened 2016-08-09 07:08 UTC
It would be nice to be able to set the component which is under maintenance on a scheduled maintenance task. 

Another thing is that a component might have a status "UNDER MAINTENANCE" so that it is not titled as major outage or something similar.

We're using 2.3.7 right now.

**Comment by jbrooksuk** [comment] 2016-08-09 07:50
Duplicate of https://github.com/CachetHQ/Cachet/issues/1546 :)

**Closed by jbrooksuk** 2016-08-09 07:50 UTC

**Comment by stipx** [comment] 2016-08-09 07:55
Is this really a duplicate of the referenced issue? Maintenance tasks are stored as incidents right? and they already have the component id field. So this would only be an addition to the UI. And the second part with the new component status would be one additional field value.
The referenced issue is related to Metrics and not to Maintenance tasks (Incidents).

**Comment by jbrooksuk** [comment] 2016-08-09 07:58
Sorry, I had a reference to the wrong issue in my clipboard, https://github.com/CachetHQ/Cachet/issues/495 is the right issue (closed now as it's grouped under a different issue).

In v3.0.0 we're changing the way that schedules work altogether, so they should be separate entities.

**Comment by stipx** [comment] 2016-08-09 08:03
Oh ok. Too bad this will take till v3 gets released.
Anyway, we look forward to this because we would like to transparently inform our users about ongoing maintenance for certain components.

Thanks for clarifying.

**Comment by jbrooksuk** [comment] 2016-08-09 08:08
> Oh ok. Too bad this will take till v3 gets released.

It's a big, but very cool release that we have lined up. The reasons it's in v3.0.0 are:

1. It requires refactoring scheduled maintenance out of incidents.
2. It requires design changes to better report what it is that is affected. (v3.0.0 will have a sexy new design).
3. Existing data will need to be migrated and it's a backwards incompatible change with the existing API, so we have to make this change at a reasonable version point.

**Comment by stipx** [comment] 2016-08-09 08:13
Thanks for your great work. Maybe use missed my "Edit".

> Would it be possible to at least add the new component status so that the component overview shows that this component is currently under maintenance (in stable version 2.x)?

And as I said. I'm looking gratefully forward to the v3 release :)

**Comment by anandchida** [comment] 2016-08-11 16:16
This is a feature im looking forward eagerly to as well.  Just adding component status to 2.x version will help immensely

**Comment by jbrooksuk** [comment] 2016-08-12 06:51
So you're thinking that if a Component is under maintenance, then its status should change?

**Comment by stipx** [comment] 2016-08-12 06:55
I think that would be a good idea. Because then you can see immediately that a component is under maintenance and do not have to scroll down to the timeline.

And as the scheduled maintenance task refactoring take place in v3 it would be nice to just have a new status in v2 to set it manually to "under maintenance".

**Comment by jbrooksuk** [comment] 2016-08-12 07:00
The only problem with that is that Scheduled Maintenance doesn't have an end date, so you'd then have to manually change the component status afterwards. That's why I was waiting till we refactor it, where maintenance can have a start and end date.

**Comment by stipx** [comment] 2016-08-12 07:07
Yes but for 2.x just setting and resetting the status via dashboard would ease our maintenance workflow:

- Schedule a maintenance
- When maintenance is started set the status to "UNDER MAINTENANCE"
- When maintenance is done reset the status

We're also creating incidents via a checking service and so we are able to skip incident creation when the component is under maintenance.

**Comment by jbrooksuk** [comment] 2016-08-12 07:08
Could you open a new issue regarding changing the status whilst under maintenance, please? I don't see why we couldn't.
