### ISSUE TITLE
Tooltip doesn't show up entirly

### ISSUE THREAD

**Issue by matunixe** [CachetHQ/Cachet#1647] opened 2016-03-21 22:42 UTC
On the last Firefox release the description tooltip doesn't show up entirely.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

A little screenshot :+1: 
![](https://pix.unixcorn.org/image/1458600119/original.jpg)

**Comment by GrahamCampbell** [comment] 2016-03-22 08:26
Looks fixed on the latest version to me?

**Comment by GrahamCampbell** [comment] 2016-03-22 08:26
Can you confirm https://demo.cachethq.io/ works ok?

**Closed** 2016-03-22 08:26 UTC

**Comment by jbrooksuk** [comment] 2016-03-22 08:56
Duplicate of https://github.com/CachetHQ/Cachet/issues/1626, which is still an issue :)

**Comment by matunixe** [comment] 2016-03-23 09:30
Just finished to upgrade following the instructions : https://docs.cachethq.io/docs/updating-cachet but nothing change. :(

**Comment by jbrooksuk** [comment] 2016-03-23 09:32
This isn't fixed yet. I closed this issue because I had already opened one for the same bug :)

**Comment by matunixe** [comment] 2016-03-23 09:49
Ok, I'll look after the other.
