### ISSUE TITLE
Subscriber Verification

### ISSUE THREAD

**Issue by jzielke** [cachethq/Cachet#1004] opened 2015-10-06 00:49 UTC
Does subscriber verification work correctly?  I just got everything set up with email and when I click on the verification link, it goes to the site but just displays the status page.  There is no thank you or anything saying that I was verified.

If I look at the dashboard, the emails are still listed as not verified.

**Comment by joecohens** [comment] 2015-10-06 06:13
Hey @jzielke! Have you setup your queue and queue workers or listeners? Do you have access to de db?

**Comment by jzielke** [comment] 2015-10-06 11:28
Everything appears to work fine.  Emails are sent, I can add emails through the dashboard, components and etc, just nothing is written to the database for the verified field when the link is clicked through the email. 

Not sure what else I am supposed to set up as far as queues and listeners.

**Comment by jbrooksuk** [comment] 2015-10-08 07:25
I need to confirm this is a bug in 2.0.0.

**Comment by jbrooksuk** [comment] 2015-10-08 07:32
I can't even get the subscriber email to send, I'm getting:

```
GuzzleHttp\Exception\ServerException]
  Server error: 500
```

In the console now and:

```
[2015-10-08 07:30:06] local.ERROR: exception 'GuzzleHttp\Exception\ServerException' with message 'Server error: 500' in /Users/james.brooks/Sites/cachethq/Cachet/vendor/guzzlehttp/guzzle/src/Middleware.php:68
Stack trace:
#0 /Users/james.brooks/Sites/cachethq/Cachet/vendor/guzzlehttp/promises/src/Promise.php(199): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#1 /Users/james.brooks/Sites/cachethq/Cachet/vendor/guzzlehttp/promises/src/Promise.php(152): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#2 /Users/james.brooks/Sites/cachethq/Cachet/vendor/guzzlehttp/promises/src/TaskQueue.php(60): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#3 /Users/james.brooks/Sites/cachethq/Cachet/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run()
#4 /Users/james.brooks/Sites/cachethq/Cachet/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick()
#5 /Users/james.brooks/Sites/cachethq/Cachet/vendor/guzzlehttp/promises/src/Promise.php(240): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#6 /Users/james.brooks/Sites/cachethq/Cachet/vendor/guzzlehttp/promises/src/Promise.php(217): GuzzleHttp\Promise\Promise->invokeWaitFn()
#7 /Users/james.brooks/Sites/cachethq/Cachet/vendor/guzzlehttp/promises/src/Promise.php(261): GuzzleHttp\Promise\Promise->waitIfPending()
#8 /Users/james.brooks/Sites/cachethq/Cachet/vendor/guzzlehttp/promises/src/Promise.php(219): GuzzleHttp\Promise\Promise->invokeWaitList()
#9 /Users/james.brooks/Sites/cachethq/Cachet/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /Users/james.brooks/Sites/cachethq/Cachet/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Promise\Promise->wait()
#11 /Users/james.brooks/Sites/cachethq/Cachet/vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request('post', 'https://mandril...', Array)
#12 /Users/james.brooks/Sites/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Mail/Transport/MandrillTransport.php(57): GuzzleHttp\Client->__call('post', Array)
#13 /Users/james.brooks/Sites/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Mail/Transport/MandrillTransport.php(57): GuzzleHttp\Client->post('https://mandril...', Array)
#14 /Users/james.brooks/Sites/cachethq/Cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(85): Illuminate\Mail\Transport\MandrillTransport->send(Object(Swift_Message), Array)
#15 /Users/james.brooks/Sites/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(391): Swift_Mailer->send(Object(Swift_Message), Array)
#16 /Users/james.brooks/Sites/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(181): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#17 /Users/james.brooks/Sites/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(286): Illuminate\Mail\Mailer->send(Array, Array, Object(Closure))
#18 /Users/james.brooks/Sites/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Mail\Mailer->handleQueuedMessage(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#19 /Users/james.brooks/Sites/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Jobs/DatabaseJob.php(50): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#20 /Users/james.brooks/Sites/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(208): Illuminate\Queue\Jobs\DatabaseJob->fire()
#21 /Users/james.brooks/Sites/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(159): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), '0', '0')
#22 /Users/james.brooks/Sites/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(109): Illuminate\Queue\Worker->pop('', 'default', '0', '3', '0')
#23 /Users/james.brooks/Sites/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(71): Illuminate\Queue\Console\WorkCommand->runWorker('', 'default', '0', '128', false)
#24 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#25 /Users/james.brooks/Sites/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(503): call_user_func_array(Array, Array)
#26 /Users/james.brooks/Sites/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#27 /Users/james.brooks/Sites/cachethq/Cachet/vendor/symfony/console/Command/Command.php(259): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /Users/james.brooks/Sites/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /Users/james.brooks/Sites/cachethq/Cachet/vendor/symfony/console/Application.php(878): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /Users/james.brooks/Sites/cachethq/Cachet/vendor/symfony/console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /Users/james.brooks/Sites/cachethq/Cachet/vendor/symfony/console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /Users/james.brooks/Sites/cachethq/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(100): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /Users/james.brooks/Sites/cachethq/Cachet/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 {main} {"identification":{"id":"db654758-b5b4-4c20-9930-2b807b8f7397"}} 
```

In the logs.

**Comment by billmn** [comment] 2015-10-08 08:37
@jzielke But have you enabled "Allow people to signup to email notifications?" in settings section?

**Comment by billmn** [comment] 2015-10-08 08:41
@jbrooksuk I just tested Subscription and works fine for me. I'm using the master branch.

**Comment by joecohens** [comment] 2015-10-08 18:21
It's also working fine for me. 
<img width="1025" alt="screen shot 2015-10-08 at 1 20 33 pm" src="https://cloud.githubusercontent.com/assets/1803556/10375649/66354380-6dbf-11e5-9907-827375de60cf.png">

**Comment by jbrooksuk** [comment] 2015-10-08 18:25
Must be fixed in V2.

**Closed** 2015-10-08 18:25 UTC
Labels: bug

**Comment by msc1978** [comment] 2015-12-16 14:08
Same issue here. Subscription mail only has link to main status site when choosing eg language Dutch. When switching back to English the mail is send with the correct confirmation link.
The problem is in our case the dutch language file. The part that has the activation code link is empty:
            'verify'       => [
                'text'           => 'Bevestig uw e-mail abonnement op :app_name status updates.\\n:link\\nBedankt, :app_name',
                'html-preheader' => 'Bevestig uw e-mail abonnement op :app_name status updates.',
                'html'           => '',
            ],

We copied it from the English file and now it works.

**Comment by jbrooksuk** [comment] 2015-12-16 18:16
Can you submit a PR with this change?

**Comment by msc1978** [comment] 2015-12-17 13:38
I'm sorry a PR? I don't know what you want me to do:)

**Comment by jbrooksuk** [comment] 2015-12-17 14:48
Ping @joecohens we need to update translations.

**Comment by joecohens** [comment] 2015-12-17 20:47
Mmm it should default to english it's weird that it doesn't, since we are using the `trans` helper
