### ISSUE TITLE
Delete Incident failed

### ISSUE THREAD

**Issue by dwydler** [CachetHQ/Cachet#2375] opened 2017-02-19 10:47 UTC
Today, i try to delete a incident in the internet explorer 11. I click on delete but nothing happen. The other buttons an this incident work fine. If i use Mozilla Firefox does it work.

Unfortunately we have only Internet Explorer on our systems.
We use the latest git version of Cachet.

**Comment by jbrooksuk** [comment] 2017-02-19 10:48
I don't have IE 11 to test with, could someone please look into this for me? :)

**Comment by dwydler** [comment] 2017-02-23 11:39
I do not know what to look for.
But i can give you access to a windows 7 via teamviewer if you want.

**Comment by Jamesking56** [comment] 2017-03-07 16:39
I have IE11 at home, I'll try tonight on a clean install and report back here any console errors or anything @jbrooksuk

**Comment by Jamesking56** [comment] 2017-03-07 20:34
Update for you.

Just tested in Windows 10, IE 11.447.14393.0, Cachet v2.3.10 and I cannot reproduce the problem. I click 'delete' on an incident and it pops up with the SweetAlert asking for confirmation. When I accept the modal the page refreshes and the incident is gone.

Please can you clarify your specific issue @dwydler ?

**Comment by jbrooksuk** [comment] 2017-03-08 22:38
Thanks @Jamesking56, I really appreciate that!

If we can get more info, I'll re-open the issue.

**Comment by dwydler** [comment] 2017-03-09 09:45
Sorry for the delay... After the comment from @Jamesking56 i tested it on Windows 10 (same version) and there it does not work. I use the latest git version of cachet (2.4.0-dev).

**Comment by Jamesking56** [comment] 2017-03-09 09:55
@dwyler have you tried the latest stable v2.3.10?

**Comment by dwydler** [comment] 2017-03-09 17:57
@Jamesking56 No. Why i should install an old version? For reference?

**Comment by jbrooksuk** [comment] 2017-03-09 19:14
@Jamesking56 you can try on https://demo.cachethq.io

**Comment by jbrooksuk** [comment] 2017-03-09 19:14
Do you have anything in the console?

**Comment by dwydler** [comment] 2017-03-10 17:22
How can i get the console output?

I also do some tests on your demo installation. There I could delete incidents, but you use there version 2.3.11-dev.

**Comment by jbrooksuk** [comment] 2017-03-10 21:38
I think in IE you press F12?

**Comment by dwydler** [comment] 2017-03-11 10:46
ah, you mean the dev tools in the browser. :-)

console output:
SCRIPT5009: "Promise" ist undefiniert
Datei: all-82aa10ad4b.js, Zeile: 1405, Spalte: 12217

debugger output:
http://pastebin.com/Pj9bmzGT

**Comment by jbrooksuk** [comment] 2017-03-12 19:21
We can polyfill `Promise`. I'll sort it.

**Comment by jbrooksuk** [comment] 2017-03-12 19:24
Hmm, we need to rewrite the JS to handle this.

**Comment by jbrooksuk** [comment] 2017-03-18 09:05
Let me know if v2.4 works for you now.

**Comment by dwydler** [comment] 2017-03-18 09:59
I have done a update the the newst git version.

Output:
HTML1300: Navigation wurde ausgeführt.
Datei: incidents
SCRIPT5009: "Promise" ist undefiniert
Datei: all-0c984282c4.js, Zeile: 23, Spalte: 1237

Debugfile: https://my.pcloud.com/publink/show?code=XZlTc6ZyuFpK6OdkjuAsdDi6t8AhQuawIhk

**Comment by jbrooksuk** [comment] 2017-07-17 21:22
Should now be fixed by https://github.com/CachetHQ/Cachet/commit/e5c3ff5e33fe5b2d6e11855515234190472a75f0

**Closed by jbrooksuk** 2017-07-17 21:22 UTC
Labels: bug, help-wanted
