### ISSUE TITLE
Allow multiple components to be selected for an incident

### ISSUE THREAD

**Issue by GoMDTerps** [CachetHQ/Cachet#2437] opened 2017-03-17 18:33 UTC
As a user, I would like to be able to select multiple components for an incident so that I may report an issue across multiple platforms.

**Comment by jbrooksuk** [comment] 2017-03-17 20:36
Duplicate of https://github.com/CachetHQ/Cachet/issues/1844 :)

**Closed by jbrooksuk** 2017-03-17 20:36 UTC
