### ISSUE TITLE
/setup is broken 

### ISSUE THREAD

**Issue by praneet12** [CachetHQ/Cachet#3213] opened 2018-08-09 08:46 UTC
-I have done each step as given in https://docs.cachethq.io/v1.0/docs/installing-cachet.

-I am using tag 2.3.6, php 7.2.8 
  
When I am visiting any end points 
/api/v1
/dashboard/
/setup
/admin

Output logs 

```[Thu Aug  9 12:55:26 2018] ::1:59962 [500]: /setup - Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/Users/praneet....', 51, Array)
#1 /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
#3 /Users/praneet.drolia/Cachet/bootstrap/cache/compiled.php(2163): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#5 {main}
  thrown in /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51
[Thu Aug  9 12:55:26 2018] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/Users/praneet....', 51, Array)
#1 /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 /Users/praneet.drolia/Cachet/bootstrap/cache/compiled.php(2163): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 /Users/praneet.drolia/Cachet/bootstrap/cache/compiled.php(2181): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Componen in /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51
```

**Comment by Atriusftw** [comment] 2018-08-09 11:37
Please search before creating an issue. This is a duplicate of https://github.com/CachetHQ/Cachet/issues/1996

You'll have to use PHP 5.6 on Cachet 2.3.

**Comment by praneet12** [comment] 2018-08-10 05:36
- [x] chmod -R 777 storage

- [x] rm -rf bootstrap/cache/*

Still getting 500 in /setup

**Closed** 2018-08-11 07:40 UTC
Labels: triage
