### ISSUE TITLE
Should Component/tag be a ManyToMany relation?

### ISSUE THREAD

**Issue by anthonybocci** [CachetHQ/Cachet#3004] opened 2018-04-09 20:01 UTC
**Affected feature** : Components (create and update at least)
**How to reproduce**:
- Go to `/dashboard/components/create`
- Fill the form
- Submit

**Exception thrown**: `BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::sync()`.
**Note**: The operation is done on a fresh install and a fresh database. The component is successfully created but the exception is thrown when calling calling `$component->tags()->sync()`

The main problem is in ComponentController:210, the `sync()` method is declared only for the ManyToMany relations.
It seems Component and Tag are used as if they had a ManyToMany relation, but they are not declared like so. Also, there is no table `component_tag`.

Cachet version: 2.4 (3c51e5115a187c063efbc7a2e1167fa579b01aa0)
PHP 7.2.3

Please see the full log:
```
[2018-04-09 17:49:31] development.ERROR: BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::sync() in /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2445
Stack trace:
#0 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1254): Illuminate\Database\Query\Builder->__call('sync', Array)
#1 [internal function]: Illuminate\Database\Eloquent\Builder->__call('sync', Array)
#2 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(356): call_user_func_array(Array, Array)
#3 /home/anthony/public_html/Cachet-test/app/Http/Controllers/Dashboard/ComponentController.php(210): Illuminate\Database\Eloquent\Relations\Relation->__call('sync', Array)
#4 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\ComponentController->createComponentAction()
#5 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#6 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('createComponent...', Array)
#7 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(CachetHQ\Cachet\Http\Controllers\Dashboard\ComponentController), 'createComponent...')
#8 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#9 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#10 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /home/anthony/public_html/Cachet-test/app/Http/Middleware/Authenticate.php(61): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#35 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#36 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#37 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#38 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /home/anthony/public_html/Cachet-test/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#46 /home/anthony/public_html/Cachet-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#47 /home/anthony/public_html/Cachet-test/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#48 {main} {"identification":{"id":"5e7be334-f568-4749-966b-ff9d5739d24f"}}
```

**Comment by jbrooksuk** [comment] 2018-04-20 08:30
Closed by https://github.com/CachetHQ/Cachet/pull/3017

**Comment by anthonybocci** [comment] 2018-05-14 13:00
@jbrooksuk The error was fixed indeed, but it's no longer true. When updating the source code, I've the exactly same error. With a fresh install the error is there, as if the database wasn't valid.

**Comment by jbrooksuk** [comment] 2018-05-15 12:56
Ah, I wonder if this because I changed the relationship when making it into a trait.

**Comment by jbrooksuk** [comment] 2018-05-15 12:56
We probably need some tests in place to check that the relationships act correctly, rather than just functional based stuff.

**Comment by anthonybocci** [comment] 2018-05-15 13:04
I agree, we need more tests. Perhaps Travis could do that? When pushing on Github, some tests would be executed to CRUD incidents, components and so on.
It would prevent us to push an unusable version, it would give us a better product.

**Comment by jbrooksuk** [comment] 2018-05-15 13:35
Yeah, we can turn on branch protection if we wished. I think once we've played around with 2.4 a bit more and we're nearing the big core changes being completed, we should look at that in more depth.

**Comment by anthonybocci** [comment] 2018-05-15 13:52
I'm afraid we are loosing stability on the project. The project is growing and we are more contributors, so we really need to set rules and tests. Otherwise we loose quality by pushing code that is not stable enough.
You speak about playing around 2.4, we also need to manage the roadmap!

**Comment by DoNotSpamPls** [comment] 2018-05-27 14:29
I can confirm that I'm getting the same error on a fresh install from the 2.4 branch, which has the "fix" (couldn't use 2.3, since I'm on PHP7).

**Comment by lucasdcrk** [comment] 2018-06-04 12:12
I also have this error
And I can't use 2.3 neither

**Comment by jbrooksuk** [comment] 2018-06-14 06:37
Right, I've had a look at the code and since moving to the polymorphic relation in tags (so that we can tag other things) we can't use ManyToMany.

I'll need to look into where we're calling `sync` and fix the code, but this will be done later.

**Comment by jbrooksuk** [comment] 2018-06-14 06:37
@DoNotSpamPls and @lucasdcrk how come you can't use 2.3?

**Comment by jbrooksuk** [comment] 2018-06-14 06:37
Oh, I've just read about PHP 7.

**Comment by jbrooksuk** [comment] 2018-06-16 21:33
@anthonybocci can you test https://github.com/CachetHQ/Cachet/pull/3087?

**Comment by anthonybocci** [comment] 2018-06-18 08:03
@jbrooksuk I've tested it and I am able to create a component, with or without tags! 👍 

Just a remark, when the form isn't valid (ex: the description is empty) the form should be filled again.

**Closed** 2018-06-18 20:37 UTC
Labels: bug, in progress
