### ISSUE TITLE
Time zone support

### ISSUE THREAD

**Issue by brianjking** [cachethq/Cachet#299] opened 2015-01-06 05:33 UTC
Is there a way to specify the time zone of the application globally or component by component? Thanks!

**Comment by jbrooksuk** [comment] 2015-01-06 08:28
Not via the Dashboard, but you can manually edit the `app/config/app.php` configuration file. We're going to add a panel for managing that kind of stuff though.

**Comment by jbrooksuk** [comment] 2015-01-06 09:02
Duplicate of #281.

**Closed by jbrooksuk** 2015-01-06 09:02 UTC
Labels: enhancement
