### ISSUE TITLE
Message during maintenance!

### ISSUE THREAD

**Issue by ToggleIP** [CachetHQ/Cachet#2986] opened 2018-03-31 20:06 UTC
Hi,

It would be nice if they add a "Under Maintenance" mode.

Right now they only have Operational  Performance Issues  Partial Outage  Major Outage.

It would also be nice if they add that if your scheduled maintenance starts that the maintenance stays at the top like this http://prntscr.com/iz1oh7

I hope this could be added.

Thanks

**Comment by anthonybocci** [comment] 2018-04-01 21:05
Hi,

I agree with you on that point, during the maintenance it would be great to have a message or banner that explains it. I think there already is an issue about it, no?
I'll tell James about that and other things to think about in the roadmap.

Please use a clearer title for your issue, only `Request` is not pretty clear. `[Request] Message during maintenance` could be an idea.

**Comment by jbrooksuk** [comment] 2018-04-02 16:17
This is a duplicate of https://github.com/CachetHQ/Cachet/issues/2782

**Closed by jbrooksuk** 2018-04-02 16:17 UTC
Labels: enhancement

**Comment by jbrooksuk** [comment] 2018-04-02 16:20
Which is actually a duplicate of https://github.com/CachetHQ/Cachet/issues/2051 whoops!
