### ISSUE TITLE
v2.1.0 install/upgrade broken

### ISSUE THREAD

**Issue by mbravorus** [CachetHQ/Cachet#1463] opened 2016-02-07 23:51 UTC
Attempting to upgrade to v2.1.0 (or an RC of it) bombs out with:

```
> php artisan clear-compiled
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class config does not exist' in /var/www/status.freef
eed.net/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
Stack trace:
#0 /var/www/status.freefeed.net/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): ReflectionClass->
__construct('config')
#1 /var/www/status.freefeed.net/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Contai
ner\Container->build('config', Array)
#2 /var/www/status.freefeed.net/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Con
tainer\Container->make('config', Array)
#3 /var/www/status.freefeed.net/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('config')
#4 /var/www/status.freefeed.net/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(1223): Illuminate\Container\Container->offsetGet('config')
#5 /var/www/status.f in /var/www/status.freefeed.net/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 738
```

if I pass --no-scripts to composer this disappears but comes back if trying to run migrations or anything else. Composer is self-updated to latest.

**Comment by GrahamCampbell** [comment] 2016-02-07 23:51
Duplicate of https://github.com/CachetHQ/Cachet/issues/1463.

**Comment by GrahamCampbell** [comment] 2016-02-07 23:52
Duplocate of https://github.com/CachetHQ/Cachet/issues/1456.

**Closed** 2016-02-07 23:51 UTC
