### ISSUE TITLE
Incident open via API fails

### ISSUE THREAD

**Issue by HerrTxbias** [CachetHQ/Cachet#2809] opened 2017-11-13 19:29 UTC
Hello!
I'm trying to open an Issue via the API. Other things like updating component statuses works, but there i get an error.

Code:
```
$data = array("name" => $title, "message" => $message, "status" => 1, "visible" => 1, "component_id" => $compid);

        $curl = curl_init(getConfigValue("cachet_url") . "api/v1/incidents");
        curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
        curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($data));
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($curl, CURLOPT_HTTPHEADER, array(
            'Content-type: application/json',
            'X-Cachet-Token: ' . getConfigValue("cachet_token")
        ));
        return curl_exec($curl);
```

Error:
```
[2017-11-13 19:25:03] production.ERROR: exception 'AltThree\Validator\ValidationException' with message 'Validation has failed.' in /var/www/status/vendor/alt-three/validator/src/ValidatingObserver.php:89
Validation errors:
The status format is invalid.
Stack trace:
#0 /var/www/status/vendor/alt-three/validator/src/ValidatingObserver.php(54): AltThree\Validator\ValidatingObserver->validate(Object(CachetHQ\Cachet\Models\Component))
#1 [internal function]: AltThree\Validator\ValidatingObserver->saving(Object(CachetHQ\Cachet\Models\Component))
#2 /var/www/status/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(348): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(CachetHQ\Cachet\Models\Component))
#4 /var/www/status/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#5 /var/www/status/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(164): Illuminate\Events\Dispatcher->fire('eloquent.saving...', Object(CachetHQ\Cachet\Models\Component), true)
#6 /var/www/status/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1686): Illuminate\Events\Dispatcher->until('eloquent.saving...', Object(CachetHQ\Cachet\Models\Component))
#7 /var/www/status/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1473): Illuminate\Database\Eloquent\Model->fireModelEvent('saving')
#8 /var/www/status/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1429): Illuminate\Database\Eloquent\Model->save(Array)
#9 /var/www/status/app/Bus/Handlers/Commands/Incident/ReportIncidentCommandHandler.php(99): Illuminate\Database\Eloquent\Model->update(Array)
#10 [internal function]: CachetHQ\Cachet\Bus\Handlers\Commands\Incident\ReportIncidentCommandHandler->handle(Object(CachetHQ\Cachet\Bus\Commands\Incident\ReportIncidentCommand))
#11 /var/www/status/vendor/alt-three/bus/src/Dispatcher.php(225): call_user_func(Array, Object(CachetHQ\Cachet\Bus\Commands\Incident\ReportIncidentCommand))
#12 [internal function]: AltThree\Bus\Dispatcher->AltThree\Bus\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\ReportIncidentCommand))
#13 /var/www/status/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(150): call_user_func(Object(Closure), Object(CachetHQ\Cachet\Bus\Commands\Incident\ReportIncidentCommand))
#14 /var/www/status/app/Bus/Middleware/UseDatabaseTransactions.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\ReportIncidentCommand))
#15 /var/www/status/vendor/laravel/framework/src/Illuminate/Database/Connection.php(527): CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->CachetHQ\Cachet\Bus\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#16 [internal function]: Illuminate\Database\Connection->transaction(Object(Closure))
#17 /var/www/status/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(317): call_user_func_array(Array, Array)
#18 /var/www/status/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#19 /var/www/status/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Illuminate\Database\DatabaseManager->transaction(Object(Closure))
#20 /var/www/status/app/Bus/Middleware/UseDatabaseTransactions.php(36): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#21 /var/www/status/app/Bus/Middleware/UseDatabaseTransactions.php(36): Illuminate\Support\Facades\DB::transaction(Object(Closure))
#22 [internal function]: CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->handle(Object(CachetHQ\Cachet\Bus\Commands\Incident\ReportIncidentCommand), Object(Closure))
#23 /var/www/status/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#24 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\ReportIncidentCommand))
#25 /var/www/status/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(CachetHQ\Cachet\Bus\Commands\Incident\ReportIncidentCommand))
#26 /var/www/status/vendor/alt-three/bus/src/Dispatcher.php(226): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /var/www/status/vendor/alt-three/bus/src/Dispatcher.php(201): AltThree\Bus\Dispatcher->dispatchNow(Object(CachetHQ\Cachet\Bus\Commands\Incident\ReportIncidentCommand), NULL)
#28 /var/www/status/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(323): AltThree\Bus\Dispatcher->dispatch(Object(CachetHQ\Cachet\Bus\Commands\Incident\ReportIncidentCommand))
#29 /var/www/status/app/Http/Controllers/Api/IncidentController.php(81): dispatch(Object(CachetHQ\Cachet\Bus\Commands\Incident\ReportIncidentCommand))
#30 [internal function]: CachetHQ\Cachet\Http\Controllers\Api\IncidentController->postIncidents()
#31 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array(Array, Array)
#32 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('postIncidents', Array)
#33 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\Api\IncidentController), Object(Illuminate\Routing\Route), 'postIncidents')
#34 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/status/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Controllers\Api\IncidentController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'postIncidents')
#40 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'postIncidents')
#41 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#42 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 /var/www/status/app/Http/Middleware/ApiAuthentication.php(67): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: CachetHQ\Cachet\Http\Middleware\ApiAuthentication->handle(Object(Illuminate\Http\Request), Object(Closure), 'true')
#47 /var/www/status/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 /var/www/status/app/Http/Middleware/Timezone.php(53): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: CachetHQ\Cachet\Http\Middleware\Timezone->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/status/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#53 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#55 /var/www/status/app/Http/Middleware/Acceptable.php(35): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 [internal function]: CachetHQ\Cachet\Http\Middleware\Acceptable->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /var/www/status/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#58 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#60 /var/www/status/vendor/barryvdh/laravel-cors/src/HandleCors.php(34): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 [internal function]: Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /var/www/status/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#63 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#65 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /var/www/status/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#67 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#68 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#69 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#70 /var/www/status/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#71 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#72 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#73 /var/www/status/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#74 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#75 /var/www/status/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#76 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#78 /var/www/status/vendor/fideloper/proxy/src/TrustProxies.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#79 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#80 /var/www/status/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#81 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#82 /var/www/status/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#83 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#84 /var/www/status/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#85 /var/www/status/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#86 /var/www/status/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#87 /var/www/status/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#88 {main} {"identification":{"id":"b797ecfc-2af6-4a4f-9381-09b5f82f960a"}}
```

I already tried some other ways, but it still doesn't work. Maybe an error in the Backend or so, idk

Regards

**Comment by jmccann** [comment] 2017-11-30 16:54
I think if you open an incident with `component_id` then you are required to provide `component_status ` also.  This is what I discovered after reading through other issues.

This should be raised back as feedback to the user via a usable error.

This also should be properly documented @ https://docs.cachethq.io/reference#incidents

**Comment by HerrTxbias** [comment] 2017-12-01 06:29
Hi!
Thank you for your response. I will try it as soon as I fixed my Windows.... (Windows broke the Boot-Partition) Then i will leave a quick message if it worked for other people who are experiencing the same error. (And sorry btw for my bad english)

**Comment by jbrooksuk** [comment] 2017-12-03 17:39
I'm not sure why this is unexpected... if a component is affected, the status needs to be supplied. In what circumstances is that not expected?

**Comment by jmccann** [comment] 2017-12-03 20:13
Maybe it is to be expected but the error returned and documentation around it are lacking.  So from that perspective it isn't really expected.  I try to capture this a little this with #2828.

Having said that, for me personally ... if I open an incident that has a status and want to identify a component as well I would expect the component to "inherit" the status of the incident if `component_status` isn't supplied.

So for me, if I open an incident with `status` of `1` or `2` then default for `component_status` could maybe be `3`.

Or if I update an incident with `status` of `4` then `component_status` could probably default to `1`.

But that is very opinionated so I'm not really advocating to make that a thing.  I think primarily error messages and documentation should be addressed around this first.  Then thoughts on if/what "sane" defaults for `component_status` based on incident `status` could later be thought about.

**Comment by jbrooksuk** [comment] 2017-12-04 08:58
What we could do is just set the default status to be what the current component status is.

**Comment by jnmcfly** [comment] 2018-02-05 13:45
Hi, get the same errors without setting a component.
I do:

`curl.exe -X POST \
-H "X-Cachet-Token:SUPERSECRECTTOKEN" \ 
-H "Content-Type:application/json" --data '{"name":"222","message":"333","status":1,"visible":1}'\ http://status.mydomain.com/api/v1/incidents/`

and get:

`{"errors":[{"id":"93720a69-e9f6-4fdf-8d89-11df48ac3692","status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax.","meta":{"details":["Das Format von name ist ung\u00fcltig.","Das Format von status ist ung\u00fcltig.","Das Format von message ist ung\u00fcltig."]}}]}`

In english: Format invalid for name, status and message

what ist wrong here?


server throws this:

https://pastebin.com/NKsAmWJ9

any suggestions?

Greetings

**Comment by jbrooksuk** [comment] 2018-06-17 17:03
@HerrTxbias @SnowBlinderP @jmccann can you guys please report back on https://github.com/CachetHQ/Cachet/pull/3099 whether this fixes the issue, please?

**Comment by SnowBlinderP** [comment] 2018-06-17 17:16
@jbrooksuk 

@HerrTxbias and i will look into it in the Next Week (18.-24.)

**Comment by jbrooksuk** [comment] 2018-06-17 17:45
No problem! I believe the issue is fixed now and we have tests to ensure this no longer happens, but I'm sure there is an edge case somewhere.

**Comment by jbrooksuk** [comment] 2023-08-12 19:33
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.

**Closed by jbrooksuk** 2023-08-12 19:33 UTC
Labels: Bug, In Progress
