### ISSUE TITLE
disable/hide component

### ISSUE THREAD

**Issue by bolshoy** [cachethq/Cachet#1095] opened 2015-11-01 13:43 UTC
Add a new status or a property to a component so it can be disabled and/or made invisible. 
Helps in the preparation stage, when you first prepare placeholders for all the required checks and then start connecting real checks and enabling components.

**Comment by jbrooksuk** [comment] 2015-11-02 18:39
Duplicate of #1082.

**Comment by bolshoy** [comment] 2015-11-03 12:18
Not exactly duplicate bug. Enabled/disabled property will help in preparing initial inventory in disabled state and enabling it when the checks are ready.

**Comment by jbrooksuk** [comment] 2015-11-03 21:17
What about the API @bolshoy? Would it return disabled components?

**Comment by bolshoy** [comment] 2015-11-04 08:07
@jbrooksuk I guess it depends whether it will break some existing implementation. Maybe return only enabled by default but provide a way (?disabled=true query string filter or else) to fetch all of them.

**Comment by jbrooksuk** [comment] 2015-11-04 08:23
For now the API will return everything. I did think about only showing them if you provide an API token?

**Comment by bolshoy** [comment] 2015-11-04 10:09
yeah, I think everything should be protected by a token.

**Closed** 2015-11-04 14:59 UTC
Labels: enhancement
