### ISSUE TITLE
Metrics interval points not working/misunderstanding

### ISSUE THREAD

**Issue by Amnacog** [CachetHQ/Cachet#1979] opened 2016-07-15 19:43 UTC
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [x] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [x] I have ran `rm -rf bootstrap/cache/*`.

### Expected behaviour

My metric is a sum type
Setting up the threshold interval between metric points to 2 (min)
because the crawler pass every 2 min

so the hour view interval would be  00:00 -> 00:02 -> 00:04

### Actual behaviour

In hour hour view, I still have 1 minutes points so there are empty spots each 2 minutes

<img width="930" alt="screen shot 2016-07-15 at 21 33 18" src="https://cloud.githubusercontent.com/assets/5430566/16886373/27b66790-4ad4-11e6-9c64-21f0dc8bf69a.png">

Thank you for your answers in advance.

**Comment by GrahamCampbell** [comment] 2016-07-15 19:51
Yeh, that's the expected behavior. I agree it's not a very good one. Hourly view is essentially broken atm.

**Comment by Amnacog** [comment] 2016-07-15 19:56
Okay so I'll just be patient then :)
thank you guys anyway.

**Comment by jbrooksuk** [comment] 2016-07-16 12:43
@GrahamCampbell maybe we should implement the changes required in https://github.com/CachetHQ/Cachet/pull/1971?

**Comment by GrahamCampbell** [comment] 2016-07-16 15:40
Closing since this is a dupe of https://github.com/CachetHQ/Cachet/issues/1922.

**Closed** 2016-07-16 15:40 UTC
