### ISSUE TITLE
Banner image upload results in 500

### ISSUE THREAD

**Issue by bert2002** [CachetHQ/Cachet#1776] opened 2016-05-09 19:20 UTC
### Your setup

- *What version of Cachet?* 2.2.2
- *What database driver? MySQL? Postgres? SQLite?* Mysql 
- *What version of PHP?* 5.5.9-1ubuntu4.16

### Expected behaviour

After a fresh installation I want to upload a banner image (png, 512x512)

### Actual behaviour

I get a 500 and following error message
```
[2016-05-09 19:16:14] production.CRITICAL: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Illuminate\Support\Facades\Str' not found' in /var/www/status/app/Http/Controllers/Dashboard/SettingsController.php:262
Stack trace:
#0 {main} {"identification":{"id":"3ac1e063-f18a-4452-9baa-26824991de61"}}
```
### Steps to reproduce

Fresh installation, login, go to settings and try to upload a banner logo

**Comment by jbrooksuk** [comment] 2016-05-09 19:45
Thanks for reporting this, however it's a duplicate of https://github.com/CachetHQ/Cachet/issues/1749

This will be fixed in v2.3.0

**Closed by jbrooksuk** 2016-05-09 19:45 UTC

**Comment by igramnet** [comment] 2017-06-12 08:51
Hello.

**Your setup**

What version of Cachet? 2.3.10
What database driver? MySQL? Postgres? SQLite? Mysql
What version of PHP? 5.6.29
**Expected behaviour**

After a fresh installation I want to upload a banner image (png, 100x32 (30kb))

**Actual behaviour**

I get a 500 and following error message

> Something went wrong on our servers while we were processing your request. An error has occurred and this resource cannot be displayed. This occurrence has been logged, and a highly trained team of monkeys has been dispatched to deal with your problem. We're really sorry about this, and will work hard to get this resolved as soon as possible. This error can be identified by bf78dcc3-fdd3-4bd4-afce-cc15eb80b590. You might want to take a note of this code.

If you do not select a banner, the settings are saved

**Comment by jbrooksuk** [comment] 2017-06-13 21:27
Can you show us your most recent log file please.
