### ISSUE TITLE
Feature request - Downtime over time

### ISSUE THREAD

**Issue by wingZero21** [cachethq/Cachet#406] opened 2015-01-19 09:10 UTC
Hi,

Just thinking that it would be awesome if there were some visual history to the downtime/outages that are recorded. 

Similar to the heroku status page here https://status.heroku.com/uptime

**Comment by wingZero21** [comment] 2015-01-19 09:19
Also it would be good when creating an incident if it gives the amount of time the outage has occured for. So it its raised on the hour and is resolved on the hour, the incident shows as occuring for 1 hour.

**Comment by jbrooksuk** [comment] 2015-01-19 09:21
Duplicate of #4.

Can you add your second comment as a new issue please.

**Closed by jbrooksuk** 2015-01-19 09:21 UTC

**Comment by meonkeys** [comment] 2016-03-24 04:06
Is there an extant issue for reporting, for example, "99.95% uptime"?

**Comment by jbrooksuk** [comment] 2016-03-24 08:31
Hi @meonkeys, nope. You can name your metric to better describe it though?

**Comment by meonkeys** [comment] 2016-03-24 17:57
Ok, I created a new feature request for these kinds of per-time-period numbers: #1656
