### ISSUE TITLE
Mailing (with Mailgun) is not working

### ISSUE THREAD

**Issue by ImFlushy** [CachetHQ/Cachet#2285] opened 2016-12-30 13:58 UTC
Hello,
I'd like to work with the subscribing to events.

These are my settings.
`MAIL_DRIVER=mailgun
MAIL_HOST=smtp.mailgun.org
MAIL_PORT=587
MAIL_USERNAME=mydomain
MAIL_PASSWORD=key-xxxxxxxxxxxxxxxxxxxxxxx
MAIL_ADDRESS=downtime@mydomain.eu
MAIL_NAME="New Downtime"
MAIL_ENCRYPTION=tls`

From the docs [found here](https://docs.cachethq.io/docs/configuring-mail), I'm not fully understanding what to insert in the password and username field.
In the username field: Is it the E-Mail? The Domain?
In the password field: Is it the E-Mail-password? The secret or public API key? The domain specific key (password)?

I'd love to get this to work.

**Comment by KeiroD** [comment] 2017-01-01 22:34
Hi,

The username details are to be taken from the SMTP credentials screen in Mailgun. I understood what the documentation was telling me to get the details from.

See #1174 and #2095

**Comment by ImFlushy** [comment] 2017-01-02 11:47
Hi,
i retried it with #1174 and #2095, but still had no success.

The following is my mail-part of .env:

    MAIL_DRIVER=mailgun
    MAILGUN_DOMAIN=example.com
    MAILGUN_SECRET=<Secret API-Key from https://mailgun.com/app/dashboard>
    MAIL_HOST=smtp.mailgun.org
    MAIL_PORT=587
    MAIL_USERNAME=status@example.com
    MAIL_PASSWORD=<SMTP Creditional Password from https://mailgun.com/app/domains/example.com/credentials>
    MAIL_ADDRESS=status@example.com
    MAIL_NAME="Example's Status"
    MAIL_ENCRYPTION=tls`

**Comment by jbrooksuk** [comment] 2017-01-02 14:14
@ImFlushy there should be no reason for Mailgun to not work :)

One thing, do you have the `\`` in your `.env` file on the `MAIL_ENCRYPTION` line?

**Comment by jbrooksuk** [comment] 2017-01-02 14:14
Closing this issue as it's not a bug, but we'll help.

**Closed by jbrooksuk** 2017-01-02 14:14 UTC

**Comment by ImFlushy** [comment] 2017-01-02 14:19
@jbrooksuk No, that was just a mistake when i was trying to figure out how to insert code properly (changed my comment now).

Would be very happy if we could resolve my problem :100:

**Comment by jbrooksuk** [comment] 2017-01-02 14:30
Can you email support@alt-three.com please.

**Comment by ImFlushy** [comment] 2017-01-02 14:33
Done so, @jbrooksuk.
