### ISSUE TITLE
SQLSTATE[HY000] [2003] Can't connect to MySQL server

### ISSUE THREAD

**Issue by maanas** [cachethq/Cachet#416] opened 2015-01-24 08:03 UTC
I m trying to install the cachet, I followed the doc and every thing works ok till i try to load it in the browser. It return following error. I debugged the dsn and tested in separate php file the mysql server connects ok. 

Am i missing some thing. I m using the master clone.

**Comment by jbrooksuk** [comment] 2015-01-24 08:46
I can only assume that your MySQL details aren't correct or MySQL isn't running. Can you confirm?

**Comment by maanas** [comment] 2015-01-24 15:05
I check with exact pdo php code and they are correct

**Comment by jbrooksuk** [comment] 2015-01-24 21:21
Is MySQL running? That error isn't caused by Cachet, but by the configuration itself.

**Comment by maanas** [comment] 2015-01-25 18:11
This php scripts works good, indicating that the Mysql is running and there is no firewall, password issues. 
```
<?php
try {
    $dbh = new PDO('mysql:host=10.0.0.61;dbname=status', 'status_dba', '########');
    echo 'Connected to database';
    }
catch(PDOException $e)
    {
    echo $e->getMessage();
    }
?>
```
[cachet@status ~]$ php test.php 
Connected to database

**Comment by jbrooksuk** [comment] 2015-01-27 22:28
@joecohens any idea on this? I'm all out of ideas.

**Comment by joecohens** [comment] 2015-01-27 22:31
Can you provide a gist with your .env file config? I think it might be detecting or using another env.

**Comment by jbrooksuk** [comment] 2015-01-29 07:15
Closing as this is most not a Cachet issue as far as I can tell.

**Closed by jbrooksuk** 2015-01-29 07:15 UTC
Labels: nobug, question
