### ISSUE TITLE
Suggestion - Select multiple components on incident

### ISSUE THREAD

**Issue by gavin2812** [CachetHQ/Cachet#2559] opened 2017-06-06 19:01 UTC
Hi there,

Thanks for sharing your project, have just managed to get it working thanks to the doco and it works a treat, just what I was looking for, have also recently popped over to www.patreon.com to show my appreciation ;-)

Not sure if you have an area for suggestions, but I was hoping to be able to make a suggestion for your consideration?

Would it be possible to mark more than one component, or even a component group, as affected by an incident? Not sure if others would find this useful or not, but I have a number of groups and components and some of them reside on the same infrastructure, so it would be handy to be able to multiple select components or whole groups as affected.

Thank you, and apologies if there is a better place to post this.

Thank you.

**Comment by Naspyy** [comment] 2017-06-07 11:54
Fully agree with that.
Duplicate of #1844 anyways :)

**Comment by jbrooksuk** [comment] 2017-06-07 11:58
> Thanks for sharing your project, have just managed to get it working thanks to the doco and it works a treat, just what I was looking for, have also recently popped over to www.patreon.com to show my appreciation ;-)

Thanks @gavin2812!

We're going to close this as a duplicate of https://github.com/CachetHQ/Cachet/issues/1844

I'd love to see someone implement this soon :)

**Closed by jbrooksuk** 2017-06-07 11:58 UTC
