### ISSUE TITLE
Deploy to Heroku - Cannot login with Admin Account

### ISSUE THREAD

**Issue by mcvic1rj** [cachethq/Cachet#183] opened 2015-01-01 08:51 UTC
After deploying to heroku and setting up and admin account, you cannot log in.

You may receive a page saying "Whoops, looks like something went wrong." when attempting to log in.

**Comment by jbrooksuk** [comment] 2015-01-01 09:35
Duplicate of #163.

**Closed by jbrooksuk** 2015-01-01 09:35 UTC
Labels: duplicate

**Comment by jbrooksuk** [comment] 2015-01-01 11:13
This is now fixed by the way.
