### ISSUE TITLE
Issues installing on EC2 w/ ServerPilot 

### ISSUE THREAD

**Issue by brianjking** [cachethq/Cachet#255] opened 2015-01-02 22:23 UTC
Hello,

I have an AWS EC2 instance that I attempted to install Cachet onto and was unsuccessful. Can you please help me get this installed for EC2 managed with ServerPilot? 

https://serverpilot.io/community/

ServerPilot uses a self install of composer, PHP, MySQL, Apache & NGINX so it's a bit strange sometimes. I'm not sure if Laravel needs to be installed separately or not. 

Thanks!

**Comment by jbrooksuk** [comment] 2015-01-02 22:24
Did you have any error messages whilst installing?

**Comment by GrahamCampbell** [comment] 2015-01-02 22:27
I assume this is due to not having apcu...

**Comment by jbrooksuk** [comment] 2015-01-02 22:27
That's a good point @GrahamCampbell, I keep forgetting we've enabled apcu.

**Comment by jbrooksuk** [comment] 2015-01-02 22:28
@brianjking can you try following this [tutorial](http://garridodiaz.com/install-apcu-serverpilot-php-5-6/) and report back.

**Comment by jbrooksuk** [comment] 2015-01-04 00:19
@brianjking did you have a chance to follow the tutorial? I don't have an EC2 instance to play with this I'm afraid, so we're relying on you :)

**Comment by brianjking** [comment] 2015-01-06 01:47
I'm still working on this. I think I may be confused on the database.php file creation steps. Can you please clarify which file I modify to setup a MySQL db?

**Comment by jbrooksuk** [comment] 2015-01-06 06:45
You'll need an env file still. You just set DB_DRIVER to MySQL.

**Comment by jbrooksuk** [comment] 2015-01-06 09:03
@brianjking check out the [install document](https://github.com/cachethq/Cachet/blob/master/docs/setup/install.md#configuring-a-database).

**Comment by jbrooksuk** [comment] 2015-01-09 22:28
@brianjking I'm going to close this now as I think the issue is fixed with the recent changes.

**Closed by jbrooksuk** 2015-01-09 22:28 UTC
Labels: bug
