### ISSUE TITLE
php artisan down not working

### ISSUE THREAD

**Issue by Perflyst** [CachetHQ/Cachet#3472] opened 2019-02-17 13:00 UTC
I just updated to latest 2.4 branch, `php artisan down` has no affect in the front end. The admin dashboard and also the default status page still works and no maintenance site is shown.
I diff'ed the file `artisan` before and after the down - up commands, it is always the same.

**Comment by jbrooksuk** [comment] 2019-02-17 14:18
Can you confirm that the `bootstrap/cache` directory is writeable?

**Comment by Perflyst** [comment] 2019-02-17 14:38
```
$ ls -lad bootstrap/cache
drwxrwxr-x. 2 calypso calypso 100 Feb 17 13:51 bootstrap/cache
```
and
```
$ ls -la bootstrap/cache
total 364
drwxrwxr-x. 2 calypso calypso    100 Feb 17 13:51 .
drwxrwxr-x. 4 calypso calypso     68 Feb  2 15:41 ..
-rw-rw-r--. 1 calypso calypso  26935 Feb 17 13:51 config.php
-rw-rw-r--. 1 calypso calypso     14 Oct 31 21:17 .gitignore
-rwxrwxr-x. 1 calypso calypso   2692 Feb  2 15:46 packages.php
-rw-rw-r--. 1 calypso calypso 313867 Feb 17 13:51 routes.php
-rw-rw-r--. 1 calypso calypso  17024 Feb  2 15:46 services.php
```

**Comment by jbrooksuk** [comment] 2019-02-18 08:28
I've confirmed this on v2.4 - it looks like a bug.

**Comment by Perflyst** [comment] 2019-02-18 09:20
Can we update without maintenace mode or is it risky?

**Comment by jbrooksuk** [comment] 2019-02-18 14:03
This is now fixed.

Upgrades are pretty quick, by the way.

**Closed** 2019-02-18 14:06 UTC
Labels: Bug
