### ISSUE TITLE
e-mail subscribers are immediately verified

### ISSUE THREAD

**Issue by n0mer** [cachethq/Cachet#855] opened 2015-08-02 11:11 UTC
Hi,

when i subscribe, new e-mail address is immediately in "Verified" state on `/dashboard/subscribers` page.

Also, `/api/v1/subscribers` shows the foolowing for this user:

```
id: "5",
email: "<hidden>",
verify_code: "<hidden>",
verified_at: "2015-08-02 13:09:20",
created_at: "2015-08-02 13:09:13",
updated_at: "2015-08-02 13:09:13",
deleted_at: null
```

**Comment by jbrooksuk** [comment] 2015-08-02 21:25
What database are you using?

**Comment by LinHub** [comment] 2015-08-03 01:40
I can confirm this building automatically using the Docker script and current git source. It uses the MySQL installed via the Docker script included with GIT.

**Comment by n0mer** [comment] 2015-08-03 07:40
@jbrooksuk 

Here is corresponding snippet of environment configuration

```
    -e CACHE_DRIVER=redis \
    -e SESSION_DRIVER=redis \
    -e QUEUE_DRIVER=redis \
    -e DB_DRIVER=mysql \
```

**Comment by jbrooksuk** [comment] 2015-08-03 07:56
I've created a subscriber from within the dashboard and the `verified_at` field is `NULL` as expected. Are you using the API?

**Comment by jbrooksuk** [comment] 2015-08-03 07:58
Fixed in 01c690608f365c9c6ceff0e3dc6b7a609e7788d4

**Closed by jbrooksuk** 2015-08-03 07:58 UTC
Labels: bug

**Comment by n0mer** [comment] 2015-08-03 08:37
no, i'm using web page

**Comment by n0mer** [comment] 2015-08-03 08:59
@jbrooksuk , excuse me - why this issue is closed?

From "the `verified_at` field is `NULL` as expected" it seems you were not able to reproduce it.

Also docker build https://registry.hub.docker.com/u/cachethq/cachet/builds_history/122451/ is broken for the last 3 attempts. Unfortunately i'm unable to see build logs.

![image](https://cloud.githubusercontent.com/assets/1862997/9034266/977534c0-39ce-11e5-99fc-7831c9d80562.png)

So don't you think that original reporter should verify that issue is fixed first?

**Comment by jbrooksuk** [comment] 2015-08-03 11:35
@n0mer lemme explain.

1. The Docker stuff is driven by the community. None of us @cachethq/owners use it and have no intention of doing so, it's not something we need to know right now, so we're very grateful for the community helping us with it. I'm contemplating 
2. I wasn't able to reproduce the error, no, I'm using MySQL too. If it's a Docker issue, then it's out of my scope.
3. I noticed that the Subscribers page is incorrectly showing that subscribers are verified (due to an incorrect condition). This is **likely** the cause of your issue. However I committed the fix to the `master` branch rather than `1.1` - I've asked @GrahamCampbell to copy this commit for us.
4. "So don't you think that original reporter should verify that issue is fixed first?" yes and no. If your issue isn't the issue that I fixed, then you're more than welcome to re-open it so we can investigate further. 

It's important to know that me closing an issue does not constitute final closure (unless locked).

**Comment by n0mer** [comment] 2015-08-03 12:30
okay, makes sense - thanks for explanation.

so my intention is to help you verify whether this is working :)

**Comment by jbrooksuk** [comment] 2015-08-03 13:13
Thanks @n0mer :)

**Comment by n0mer** [comment] 2015-08-03 14:45
so now i can confirm that after https://github.com/cachethq/Cachet/commit/90baf187247ec13e70221a6eee9d71d8146c217a "verify" functionality works.

Also #851 is fixed.

**Comment by jbrooksuk** [comment] 2015-08-03 15:12
Good stuff!
