### ISSUE TITLE
LDAP Support - Adldap2-Laravel

### ISSUE THREAD

**Issue by gonzoinc** [CachetHQ/Cachet#2568] opened 2017-06-13 12:29 UTC
Would it be possible to integrate Adldap2-Laravel LDAP functionality into Cachet? Having an LDAP option is sort of a necessity for running Cachet in any sort of actual production environment.

https://github.com/Adldap2/Adldap2-Laravel

**Comment by jbrooksuk** [comment] 2017-06-13 21:38
Duplicate of https://github.com/CachetHQ/Cachet/issues/2108 :)

**Closed by jbrooksuk** 2017-06-13 21:38 UTC
