### ISSUE TITLE
This project is dead?

### ISSUE THREAD

**Issue by anthosz** [CachetHQ/Cachet#4197] opened 2021-01-05 19:48 UTC
Hi,

It seems that there are no news since several month concerning this project. Moreover, several PR are in pending.

Do you know if this project is archived or if it's continue? If it's continue, do we have a roadmap?

Best regards,,

**Comment by anthosz** [comment] 2021-01-05 19:51
cc @jbrooksuk

**Comment by w4rc0n** [comment] 2021-01-19 19:20
Really seems like it's dead. Which sucks.

**Comment by JensErat** [comment] 2021-01-22 09:29
Also discussed in/duplicate of #4037

**Comment by sedan07** [comment] 2021-01-25 15:29
As it doesn't appear to be terribly active I've forked and started working towards getting the new features in 2.4 stable and a release out the door, although as `v2.5` (skipping 2.4) over at: https://github.com/fiveai/Cachet/tree/2.5 if anyone else is interested.

**Comment by gustavobim** [comment] 2021-01-27 16:14
@sedan07 great news. I will make sure to check that. Thanks for sharing.

**Comment by jbrooksuk** [comment] 2023-08-10 11:45
Hey 👋 

Please check out https://github.com/CachetHQ/Cachet/discussions/4342

TLDR; Cachet is back! 🎉

**Closed by jbrooksuk** 2023-08-10 11:45 UTC
