### ISSUE TITLE
Updating Component

### ISSUE THREAD

**Issue by TWG-Matt** [CachetHQ/Cachet#2370] opened 2017-02-15 14:54 UTC
Running: 2.4.0-dev

When you edit an already existing Component and then click save, you are taken to a generic 500 page.

**Comment by OzWookiee** [comment] 2017-02-16 01:37
Duplicate of https://github.com/CachetHQ/Cachet/issues/2368

**Comment by jbrooksuk** [comment] 2017-02-16 08:20
Fixed 👍

**Closed by jbrooksuk** 2017-02-16 08:20 UTC
