### ISSUE TITLE
500 server error next setup

### ISSUE THREAD

**Issue by drummerschlumpf** [CachetHQ/Cachet#3722] opened 2019-07-28 12:28 UTC
Hello, next the setup i hav an error 500 the setup staps have i done.

here the error Code: https://pastebin.com/Db5RDmYt

sry for bad english im german

thanks Drummerschlumpf

**Comment by drewklein20** [comment] 2019-07-29 20:10
Check out [#3623](https://github.com/CachetHQ/Cachet/issues/3623)

**Comment by GeekJosh** [comment] 2019-08-07 15:49
Make sure you checked out the latest tagged version (currently 2.3.18)
Initially, I went straight for the last in the list from `git tag -l` which is v2.3.9, that uses some dependency that is not PHP 7.2 compatible. v2.3.18 works fine.

**Comment by Neurozone** [comment] 2019-08-13 09:41
Same error here.
cache v2.3.9 isn't compatible with php 7.3 like the documentation said.
but the 2.4 relase has NO tag so as explained in the documentation we can't use the version 2.4

**Comment by jbrooksuk** [comment] 2019-08-14 07:01
Duplicate of https://github.com/CachetHQ/Cachet/issues/3719

**Comment by jbrooksuk** [comment] 2019-08-14 07:01
Use v2.4 for PHP 7

**Closed by jbrooksuk** 2019-08-14 07:01 UTC
Labels: triage
