### ISSUE TITLE
Fatal Error Exception: Trait 'AltThree\TestBench\ValidationTrait' not found

### ISSUE THREAD

**Issue by jamesonp** [CachetHQ/Cachet#3033] opened 2018-04-29 06:52 UTC
I'm on 2.4, did a git pull to the latest and am getting the following error when attempting to edit components:

```
Stack trace:
#0 {main} {"identification":{"id":"6c870e9e-2840-4c70-8bac-75e07f0bd9bd"}}
[2018-04-29 06:30:59] production.CRITICAL: Symfony\Component\Debug\Exception\FatalErrorException: Trait 'AltThree\TestBench\ValidationTrait' not found in /var/www/status.site.com/Cachet/app/Models/Taggable.php:24
```
I reverted back to a backup which solved the issue for me for now.

**Comment by jbrooksuk** [comment] 2018-04-29 11:06
Duplicate of https://github.com/CachetHQ/Cachet/issues/3003

You must run `composer install -o --no-dev`.

**Closed by jbrooksuk** 2018-04-29 11:06 UTC
Labels: triage

**Comment by jamesonp** [comment] 2018-04-30 03:30
Didn't solve the issue.  Still same error:

> [2018-04-30 03:26:53] production.CRITICAL: Symfony\Component\Debug\Exception\FatalErrorException: Trait 'AltThree\TestBench\ValidationTrait' not found in /var/www/status.site.com/Cachet/app/Models/Taggable.php:24
> Stack trace:
> #0 {main} {"identification":{"id":"d531d3a2-1315-4dd6-a36f-227cd3e1dbb4"}}
> 
```

Here are the results of running composer install -o --no-dev:

***@appsLVMprod2:/var/www/status.site.com/Cachet# composer install -o --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 17 updates, 0 removals
  - Updating guzzlehttp/guzzle (6.3.0 => 6.3.2): Downloading (100%)
  - Updating aws/aws-sdk-php (3.52.26 => 3.53.1): Downloading (100%)
  - Updating symfony/translation (v3.4.6 => v3.4.7): Downloading (100%)
  - Updating nesbot/carbon (1.24.2 => 1.25.0): Downloading (100%)
  - Updating nexmo/client (1.3.0 => 1.3.1): Downloading (100%)
  - Updating symfony/var-dumper (v3.4.6 => v3.4.7): Downloading (100%)
  - Updating symfony/debug (v3.4.6 => v3.4.7): Downloading (100%)
  - Updating symfony/console (v3.4.6 => v3.4.7): Downloading (100%)
  - Updating psy/psysh (v0.8.17 => v0.8.18): Downloading (100%)
  - Updating symfony/css-selector (v3.4.6 => v3.4.7): Downloading (100%)                                                                                                           - Updating symfony/finder (v3.4.6 => v3.4.7): Downloading (100%)
  - Updating symfony/http-foundation (v3.4.6 => v3.4.7): Downloading (100%)                                                                                                        - Updating symfony/event-dispatcher (v3.4.6 => v3.4.7): Downloading (100%)                                                                                                       - Updating symfony/http-kernel (v3.4.6 => v3.4.7): Downloading (100%)
  - Updating symfony/process (v3.4.6 => v3.4.7): Downloading (100%)
  - Updating symfony/routing (v3.4.6 => v3.4.7): Downloading (100%)
  - Updating twig/twig (v1.35.2 => v1.35.3): Downloading (100%)
Package graham-campbell/core is abandoned, you should avoid using it. No replace                                                                                                 ment was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.
```

**Comment by jbrooksuk** [comment] 2018-06-08 22:16
This should be fixed own

**Comment by JessicaAlan** [comment] 2018-06-13 20:33
I am still getting this error on a fresh install of 2.4.

```
[2018-06-13 20:28:01] production.CRITICAL: Symfony\Component\Debug\Exception\FatalErrorException: Trait 'AltThree\TestBench\ValidationTrait' not found in /var/www/app/Models/Taggable.php:24
Stack trace:
#0 {main} {"identification":{"id":"a364ff5c-a13d-4470-be5f-895795e14b6f"}}
```

**Comment by jbrooksuk** [comment] 2018-06-14 06:34
Sorry! This is definitely fixed now.
