### ISSUE TITLE
New Feature: Integration with LDAP

### ISSUE THREAD

**Issue by joaquin386** [CachetHQ/Cachet#2936] opened 2018-03-15 11:57 UTC
Hi Guys

Just as a future development. Consider integrating Cachet with LDAP since this way just need to have one user accross all you infra, same at the time of changing the password.

Thx

Jo

**Comment by jbrooksuk** [comment] 2018-03-15 13:38
Duplicate of https://github.com/CachetHQ/Cachet/issues/2108

**Closed by jbrooksuk** 2018-03-15 13:38 UTC
