### ISSUE TITLE
Custom settings not saving

### ISSUE THREAD

**Issue by JackWent** [CachetHQ/Cachet#1837] opened 2016-05-26 08:53 UTC
Your setup

    What version of Cachet?
    v2.3.0-RC1

    What database driver? MySQL? Postgres? SQLite?
    MySQL

    What version of PHP?
    PHP 5.6.11-1ubuntu3.2

Expected behaviour

To save custom settings on the /dashboard/settings/customization page.

Actual behaviour

No Error, says its saved and page refresh's without my settings showing.

Steps to reproduce

Try and add a custom setting, I’m finding this for enabling graphs on the stats page (i tick the box and hit apply but nothing saves)

**Comment by GrahamCampbell** [comment] 2016-05-26 09:20
Duplicate of https://github.com/CachetHQ/Cachet/issues/1833.

**Closed** 2016-05-26 09:20 UTC

**Comment by jbrooksuk** [comment] 2016-05-26 10:07
If you refresh again, the settings are saved.
