### ISSUE TITLE
How to implement i18n in app.js?

### ISSUE THREAD

**Issue by phecho** [CachetHQ/Cachet#1135] opened 2015-11-15 01:25 UTC
Is there a way to solve the problem？such as the tips of component updated.

**Comment by jbrooksuk** [comment] 2015-11-15 09:38
@AntoineAugusti started working on this previously.

**Comment by AntoineAugusti** [comment] 2015-11-15 10:54
@jbrooksuk @phecho I was just throwing out ideas in the wild, I don't plan to make something actually ready to ship. I guess this is one of the most difficult issue to tackle...

See also https://github.com/cachethq/Cachet/issues/832 and https://github.com/cachethq/Cachet/issues/974

**Comment by phecho** [comment] 2015-11-20 15:53
Hi all, 

I throw away a brick in order to get a gem .
I have implemented the featrue in my local branch from AntoineAugusti's suggestion . Now I explain to you what I thought about this problem.
Although the codes bellow have been implemented in my development environment, but I am not satisfied with myself. So just provide a way of thinking.

*  1. Add laracasts/utilities
```JSON
"laracasts/utilities": "~2.0" in composer.json
```

*  2.  Create a composer(JavascriptComposer)
```PHP
class JavascriptComposer
{
    public function compose(View $view)
    {
        JavaScript::put([
            'dashboard_components_edit_success' => trans('dashboard.components.edit.success'),
            'dashboard_components_edit_failure' => trans('dashboard.components.edit.failure')
        ]);

    }
}
```
* 3.  Add JavascriptComposer in ComposerServiceProvider.php
```PHP
$factory->composer(['dashboard.*'], JavascriptComposer::class);
```
* 4.  In config/javascript.php
```PHP
return [
    'bind_js_vars_to_this_view' => ['dashboard/partials/sub-sidebar'],
    'js_namespace' => 'Global.trans'
];
```
* 5.  In app.js
```javascript
// Sortable components.
    var componentList = document.getElementById("component-list");
    if (componentList) {
                   ......
                    success: function() {
                        (new CachetHQ.Notifier()).notify(Global.trans.dashboard_components_edit_success || 'Component orders updated.', 'success');
                    },
                    error: function() {
                        (new CachetHQ.Notifier()).notify(Global.trans.dashboard_components_edit_failure || 'Component orders not updated.', 'error');
                   }
                   ......
    }
```

@jbrooksuk @AntoineAugusti

**Comment by jbrooksuk** [comment] 2016-05-08 17:45
Moved this to v3.0.0 as it'll include a refactor of all translations.

**Comment by jbrooksuk** [comment] 2016-07-12 17:13
Heh, I never noticed that this is a duplicate of https://github.com/CachetHQ/Cachet/issues/974

**Closed by jbrooksuk** 2016-07-12 17:13 UTC
Labels: T: Question, Translations
