### ISSUE TITLE
Dissallowing public users to subscribe disables dashboard user subscription button

### ISSUE THREAD

**Issue by BBrey** [CachetHQ/Cachet#3214] opened 2018-08-09 13:52 UTC
## Reproduction
- Enable public subscribing through the dashboard
- Go to the subscribers page and you see the add button 
- Disabled public subscribing
- Go to the add subscribers page in the dashboard and you don't see the button anymore

## Version
2.3.14-dev

**Comment by Atriusftw** [comment] 2018-08-09 14:04
I belive this is a duplicate of https://github.com/CachetHQ/Cachet/issues/3177?

**Comment by BBrey** [comment] 2018-08-09 14:49
After reading it, and testing it myself it is related I think.
He is talking about the notify checkbox and i am talking about the button to add subscribers.

**Comment by jbrooksuk** [comment] 2023-08-12 19:31
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.

**Closed by jbrooksuk** 2023-08-12 19:31 UTC
Labels: triage
