### ISSUE TITLE
Graphs fail to load with 500 error

### ISSUE THREAD

**Issue by sethjones** [CachetHQ/Cachet#3920] opened 2020-01-07 15:39 UTC
Running docker version 2.4

After installation, everything appears to be working normally.  However, when attempting to add metrics graphs on the dashboard there are 500 errors.  Its appears that the request is going to /metrics/ instead of the previous /api/v1/metrics/ .

**Comment by jonathon2nd** [comment] 2020-02-14 18:48
I am experiencing this issue as well.

**Comment by jonathon2nd** [comment] 2020-02-14 22:02
To get it working I added 
```
rewrite ^/metrics/(.*)$ https://status-test.example.com/api/v1/metrics/$1 permanent;
```
to nginx config.

**Comment by jonathon2nd** [comment] 2020-02-18 18:18
This is caused by a problem with cachet CachetHQ/Cachet#3254. By adding CachetHQ/Cachet#3830 and building docker image using it, I was able to resolve this issues. Looking to see if the pull will be merged

**Comment by sowmya-vantara** [comment] 2020-05-12 04:32
Hi, I have installed cachet(2.4) with docker and i too have issue with charts display if data is less than 12 hrs. I understand by above comments that PR should be merged to get this issue resolved.

Can you provide some updates on this ?

**Comment by Fireant456** [comment] 2020-05-21 06:35
https://hub.docker.com/repository/docker/fireant456/cachet If anyone needs it temporarily

@sowmya-vantara

**Comment by jbrooksuk** [comment] 2023-08-12 19:23
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.

**Closed by jbrooksuk** 2023-08-12 19:23 UTC
Labels: triage
