### ISSUE TITLE
Setup page does not load correctly.

### ISSUE THREAD

**Issue by jcharman** [CachetHQ/Cachet#2132] opened 2016-10-04 12:37 UTC
I've installed Cachet on our Ubuntu 14.04 server running Apache2 and PHP 5.5.38 with MySQL.

The app seems to work but I'm always redirected to the setup page which doesn't appear to load correctly.

![cachet](https://cloud.githubusercontent.com/assets/15647969/19074335/9b46937c-8a37-11e6-8f55-50feba1af55d.PNG)

I can't see anything in the logs and I'm not sure where to go from here. I can provide extra info if needed.

Thanks 
Jake

**Comment by jbrooksuk** [comment] 2016-10-04 12:43
Ping @GrahamCampbell. This has happened before, hasn't it?

**Comment by jbrooksuk** [comment] 2016-10-04 18:06
FWIW, I'm pretty sure that this is an issue with the server, so I'm closing the issue **but** we'll continue to figure out the cause.

**Closed by jbrooksuk** 2016-10-04 18:06 UTC

**Comment by jcharman** [comment] 2016-10-04 18:08
Thanks,

I'm fairly sure this is a problem on our end too, I'm just looking for clues as to what might be causing it. If it's any help, I'm fairly sure PHP is working correctly since osTicket is installed and working fine on the same server.

**Comment by jbrooksuk** [comment] 2016-10-04 18:21
Are you running PHP-FPM?

**Comment by jcharman** [comment] 2016-10-04 18:24
Not as far as I know, sorry, PHP isn't my specialist subject. I installed PHP 5.5.38 using apt from [this PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php) since osTicket doesn't play nicely with a newer version of PHP.

**Comment by jcharman** [comment] 2016-10-04 19:14
Hi,

I've reinstalled Cachet and everything seems to be working. I think I had something wrong in the Apache2 config files.

Thanks for your help,
Jake

**Comment by jcharman** [comment] 2016-10-04 19:37
Argh, looks like I spoke too soon.

The setup page loads now but it hangs on the first page after I click next. Again no errors in the logs. Have you seen this before?

Jake

**Comment by jcharman** [comment] 2016-10-04 19:54
Yes they were. Murphy's law took over and I fixed it just after asking for help. I had the virtual host set up wrong so the request for the next section was going to the wrong place.

**Comment by jbrooksuk** [comment] 2016-10-04 21:44
:)

**Comment by BossManFergie** [comment] 2016-10-05 22:59
@jcharman - Can you provide anymore information as to how you fixed it? I just did two fresh installs and had the exact same setup page issue as you previously had.

**Comment by jcharman** [comment] 2016-10-05 23:43
Hi, 

I'm still mostly in the dark myself. The first time I installed, I installed in the existing /var/www/html directory instead of installing in /var/www and giving it its own Apache virtual host. I'm fairly sure the issue here (after looking at the console in Chrome whilst running the app) is that unless the app is set up exactly as described with a virtual host, the requests for various components get sent to the wrong places. For example I was having issues with requests for example.com/index.php/setup/something going to example.com/setup/something which of course returned a 404 error. 

I basically just erased the whole Cachet directory and started again ensuring I followed the documentation to the letter. I'd be happy to answer any more questions you have about my setup which I'm pleased to report is now working correctly

**Comment by jbrooksuk** [comment] 2016-10-06 07:55
Do you have `mod_rewrite` enabled?

**Comment by BossManFergie** [comment] 2016-10-06 11:43
@jbrooksuk - I do. I did notice my requests were being sent to the wrong place just as @jcharman stated his install was also doing. I had the virtualhost set up properly but it just wouldn't work for some reason. So I wrote a custom .htaccess to pretty much do the same thing the virtualhost would do and it's working fine now. Thanks for the assistance guys. :)

**Comment by ngrhd** [comment] 2017-02-23 18:24
@BossManFergie It would be very nice of you if you could please share the custom made .htaccess

**Comment by BossManFergie** [comment] 2017-02-23 19:35
@ngrhd 
```
RewriteEngine on
RewriteCond %{HTTP_HOST} ^your.website.com$ [NC,OR]
RewriteCond %{HTTP_HOST} ^www.your.website.com.com$
RewriteCond %{REQUEST_URI} !public/
RewriteRule (.*) /public/$1 [L]
```
