### ISSUE TITLE
Propagate activity into a chat service.

### ISSUE THREAD

**Issue by Jamie-Owen** [CachetHQ/Cachet#1651] opened 2016-03-23 17:34 UTC
Is there any plan to add functionality to allow users to integrate Cachet with a chat service like Slack?

It would be nice if a component changing state or an incident being created triggered a message to a chat channel.

I believe statuspage.io provide this functionality too, see [here](http://help.statuspage.io/knowledge_base/topics/pipe-activity-log-into-slack?from_search=true).

**Comment by jbrooksuk** [comment] 2016-05-08 17:46
Ah, this is a duplicate of https://github.com/CachetHQ/Cachet/issues/1023

**Closed by jbrooksuk** 2016-05-08 17:46 UTC
Labels: T: Feature, up-for-grabs
