### ISSUE TITLE
cant install cachet because of a php error

### ISSUE THREAD

**Issue by jsargent7089** [CachetHQ/Cachet#2646] opened 2017-07-19 16:26 UTC
PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('config')
#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('config', Array)
#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('config', Array)
#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('config')
#4 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(1223): Illuminate\Container\Container->offsetGet('config')
#5 /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandler.php(60): Illuminate\Container\Container->__get('config')
 in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734

**Comment by jsargent7089** [comment] 2017-07-19 16:26
if (! $reflector->isInstantiable()) {
            if (! empty($this->buildStack)) {
                $previous = implode(', ', $this->buildStack);

                $message = "Target [$concrete] is not instantiable while building [$previous].";
            } else {
                $message = "Target [$concrete] is not instantiable.";
            }

            throw new BindingResolutionException($message);
        }

**Comment by jbrooksuk** [comment] 2017-07-19 19:29
Try running `rm -rf bootstrap/cache{,t}/*`

**Comment by jsargent7089** [comment] 2017-07-20 01:45
did not work

**Comment by jsargent7089** [comment] 2017-07-20 01:49
i still get the same error

**Comment by GrahamCampbell** [comment] 2017-07-20 07:03
Can you post the whole stack trace please?

**Comment by jsargent7089** [comment] 2017-07-23 02:55
server@status:/var/www/html/Cachet# php artisan key:generate
PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('config')
#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('config', Array)
#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('config', Array)
#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('config')
#4 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(1223): Illuminate\Container\Container->offsetGet('config')
#5 /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandler.php(60): Illuminate\Container\Container->__get('config')
 in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734

server@status:/var/www/html/Cachet# php artisan app:install
PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:734

Stack trace:
#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('config')
#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('config', Array)
#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('config', Array)
#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('config')
#4 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(1223): Illuminate\Container\Container->offsetGet('config')
#5 /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandler.php(60): Illuminate\Container\Container->__get('config')
 in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734

**Comment by jsargent7089** [comment] 2017-07-23 02:55
there you go

**Comment by jbrooksuk** [comment] 2017-07-25 10:53
@GrahamCampbell more info for you!

**Comment by gregkare** [comment] 2017-07-29 11:28
I ran into the same issue and managed to fix it. It was caused by spaces in my `.env` file in one of the values. Wrapping the value in double quotes fixed the issue

**Comment by jbrooksuk** [comment] 2017-07-30 12:23
@gregkare's suggestion makes sense. I'm closing the issue but if it's not fixed, let's re-open.

**Closed by jbrooksuk** 2017-07-30 12:23 UTC

**Comment by JustinCarmony** [comment] 2017-11-01 21:24
@gregkare that fixed my issue, I had a minus/dash sign in a password field and it caused the error for me. Wrapping in quotes works to fix it.

**Comment by jbrooksuk** [comment] 2017-11-04 09:00
Ah yes, any character such as spaces, dashes etc need to have the whole value wrapped in quotes.
