### ISSUE TITLE
Metric graph is blank only in Firefox

### ISSUE THREAD

**Issue by andrewgoktepe** [cachethq/Cachet#941] opened 2015-09-10 17:11 UTC
I am trying to track down an issue with a metric I have added to a cachet dashboard.  In Firefox, the graph is always blank.  In Chrome and Safari it works fine.  I have tested on both OS X Yosemite and Windows 7 with the same results.  The Firefox web console does not show any errors. 

The status page is publicly accessible so you can see for yourself: https://status.savantcs.com
(The page is still under development so it may show fake incidents or be intermittently unavailable)

Screen shot from Chrome:
![image](https://cloud.githubusercontent.com/assets/3442168/9795104/a55cb5f2-57a3-11e5-94be-75a11fd45b39.png)

Screen shot from Firefox
![image](https://cloud.githubusercontent.com/assets/3442168/9795108/aa1e3b38-57a3-11e5-9984-6a3f0543262e.png)

The Cachet demo does not have this issue in Firefox so I wonder if it is something related to my data.  We are using MySQL for the database.  The records in metric_points look like this:

    mysql> select * from metric_points order by created_at asc limit 5;
    +----+-----------+---------+---------------------+---------------------+
    | id | metric_id | value   | created_at          | updated_at          |
    +----+-----------+---------+---------------------+---------------------+
    |  1 |         1 | 207.000 | 2015-09-09 21:20:03 | 2015-09-09 21:20:03 |
    |  2 |         1 | 201.000 | 2015-09-09 21:20:05 | 2015-09-09 21:20:05 |
    |  3 |         1 | 212.000 | 2015-09-09 21:21:03 | 2015-09-09 21:21:03 |
    |  4 |         1 | 220.000 | 2015-09-09 21:22:03 | 2015-09-09 21:22:03 |
    |  5 |         1 | 213.000 | 2015-09-09 21:23:03 | 2015-09-09 21:23:04 |
    +----+-----------+---------+---------------------+---------------------+
    5 rows in set (0.00 sec)

This is the latest master code for Cachet which is currently on commit 2fbc044057498621e7c9268f3edbdc27e33b54e6. 

In case it's helpul, I was just looking at this Firefox bug which may or may not be related:
https://bugzilla.mozilla.org/show_bug.cgi?id=661452

**Comment by jbrooksuk** [comment] 2015-09-10 20:23
1. You're using an unreleased version of Cachet, so bugs may occur.
2. Thanks for reporting this, I don't use Firefox so probably wouldn't have seen this.
3. The issue is caused by an error with the JSON.

**Comment by jbrooksuk** [comment] 2015-09-10 20:25
Closed by 536ae3502d4e4018e38d919ca87a4b5d93c90d17

**Closed by jbrooksuk** 2015-09-10 20:25 UTC
Labels: bug
