### ISSUE TITLE
logo upload fail class str not found

### ISSUE THREAD

**Issue by jmchapman84** [CachetHQ/Cachet#1749] opened 2016-05-04 15:14 UTC
Just performed a clean install of v2.2.2 and everything works fine apart from the logo upload in Themes

When uploading, I get a 500 Error with the following in the larvel log:

[2016-05-04 15:06:57] production.CRITICAL: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Illuminate\Support\Facades\Str' not found' in /srv/sites/status/www/Cachet/app/Http/Controllers/Dashboard/SettingsController.php:262
Stack trace:
#0 {main} {"identification":{"id":"745b8a30-bf8d-48de-8a01-35118089e820"}} 

Any Ideas?

**Comment by GrahamCampbell** [comment] 2016-05-04 15:38
Thanks for the report. This will be fixed in the v2.3.0 release.

**Comment by eladnava** [comment] 2016-06-06 09:55
The issue is here:
https://github.com/CachetHQ/Cachet/blob/9d9d3b2e6cbaa49a26c7ef3ac5d82a857a039002/app/Http/Controllers/Dashboard/SettingsController.php#L22

It should be:
```
use Illuminate\Support\Str;
```

Isn't it worth releasing a patch version for `v2.2` @GrahamCampbell?

**Comment by jbrooksuk** [comment] 2016-06-06 10:04
I'll release a 2.2 patch version.

**Comment by eladnava** [comment] 2016-06-06 10:05
@jbrooksuk Thanks so much! =) Loving Cachet so far.

**Comment by jbrooksuk** [comment] 2016-06-06 10:07
Thanks! 😍

**Comment by eladnava** [comment] 2016-06-06 10:16
@jbrooksuk Check out my blog post about Cachet 👍 
https://eladnava.com/set-up-a-service-status-page-for-free-with-cachet/

One thing I'd recommend is updating the installation docs, but other than that, loving it!

**Comment by jbrooksuk** [comment] 2016-06-06 10:21
I've released 2.2.3 - https://github.com/CachetHQ/Cachet/releases/tag/v2.2.3

The installation docs is going to be massively rewritten for 2.3 onwards :)

**Comment by eladnava** [comment] 2016-06-06 10:22
@jbrooksuk Awesome!

Feel free to use my blog post for some of the commands, it's got all the required PHP dependencies as well.

**Comment by jbrooksuk** [comment] 2016-06-06 10:23
Cheers! I'll probably share the post on our [Twitter](https://twitter.com/CachetHQ) at some point :)

**Closed** 2016-06-06 10:23 UTC
Labels: T: Bug
