### ISSUE TITLE
User level improvements

### ISSUE THREAD

**Issue by jhamilton09** [CachetHQ/Cachet#1806] opened 2016-05-23 20:40 UTC
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

[ X ] You're running the latest release version of Cachet.
[ X ] Ensure that you're running at least PHP 5.5.9, you can check this by running php -v
[ X ] You've ran rm -rf bootstrap/cache/* from the root of your Cachet installation.
To help us better understand your issue, please answer the following — cheers!

**Your setup:**

What version of Cachet? 2.2.2
What database driver? MySQL? Postgres? SQLite? MySQL
What version of PHP? 7.0.3

**Expected behavior**

As an administrator, I should be able to update a team member's user level.

Users should not be able to add or rearrange components or edit site settings, only add and update incidents.

**Actual behavior**

I can only update user name, email, and password.

Users can do everything admin level except for editing team members, I believe.

Steps to reproduce
View Team member page and see only the three fields for user name, email, and password.

As a user, "accidentally" delete a component or add an unapproved component.

**Comment by GrahamCampbell** [comment] 2016-05-23 21:28
Admins are only admins in the way they can mess with other user accounts. Users should be trusted enough to be admins over the actual status page. I guess you're requesting more fine grained control there?

**Comment by jhamilton09** [comment] 2016-05-23 21:33
Yeah, I think users should be able to manage incidents but they should not be able to change site settings like the site description or CSS customizations. The way I'm setting up my instance, we have a variety of service owners that will log incidents but I don't trust them to not "accidentally" change some site setting. More fine-grained control would be a welcome addition.

**Comment by jbrooksuk** [comment] 2016-05-24 06:42
This is essentially a duplicate of #876.

**Closed by jbrooksuk** 2016-05-24 06:42 UTC

**Comment by jhamilton09** [comment] 2016-05-24 12:41
I agree, the fine-grained control is a duplicate of #876 but the other part of this issue is the ability to edit a team member and choose whether they are a User or an Admin. That should be in the Team controls for an Admin to be able to change.

**Comment by jbrooksuk** [comment] 2016-05-24 12:47
> I agree, the fine-grained control is a duplicate of #876 but the other part of this issue is the ability to edit a team member and choose whether they are a User or an Admin.

Can you open a separate issue for this please? It keeps requests, bugs and duplicates easier to manage :) Thank you!
